
no_index: 
  directory: 
    - inc
    - t
generated_by: Module::Install version 0.62
distribution_type: module
version: 0.02
name: asa
author: Adam Kennedy <cpan@ali.as<
license: perl
build_requires: 
  Test::More: 0.47
  File::Spec: 0.80
requires: 
  base: 0
  perl: 5.005
  Carp: 0
abstract: Lets your class/object say it works like something else
